# Generated by Django 3.1.4 on 2020-12-04 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_auto_20201204_0207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carousel',
        ),
    ]
