# Generated by Django 3.1.4 on 2020-12-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_carousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carousel',
            old_name='Item',
            new_name='item',
        ),
    ]
