# Generated by Django 3.1.4 on 2020-12-04 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_auto_20201204_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
            preserve_default=False,
        ),
    ]
