# Generated by Django 3.1.4 on 2020-12-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_carousel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='user',
        ),
    ]
