# Generated by Django 3.1.4 on 2020-12-05 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0012_delete_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('nat', 'Nature'), ('fam', 'Family'), ('ani', 'Animals'), ('christ', 'Christmas'), ('east', 'Easter'), ('city', 'City'), ('fun', 'Fun')], default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(choices=[('pic', 'Picture'), ('mod', 'Hand-made model')], default=None, max_length=7),
        ),
    ]
