# Generated by Django 3.1.4 on 2020-12-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_auto_20201205_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('nat', 'Nature'), ('fam', 'Family'), ('ani', 'Animals'), ('christ', 'Christmas'), ('east', 'Easter'), ('city', 'City'), ('fun', 'Fun'), ('other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
