# Generated by Django 3.1.4 on 2020-12-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_auto_20201206_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Nature', 'Nature'), ('Family', 'Family'), ('Animals', 'Animals'), ('Christmas', 'Christmas'), ('Easter', 'Easter'), ('City', 'City'), ('Fun', 'Fun'), ('Other', 'Other')], default='other', max_length=20, null=True),
        ),
    ]
